server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /continuuuum_editor {
        return 301 /continuuuum_editor/;
    }

    location /continuuuum_editor/ {
        alias /usr/share/nginx/html/library/continuuuum_editor_webgl/;
        try_files $uri $uri/ /library/continuuuum_editor_webgl/index.html;
    }

    location /library/continuuuum_editor_webgl/ {
        try_files $uri $uri/ /library/continuuuum_editor_webgl/index.html;
    }

    location / {
        try_files $uri $uri/ /library/continuuuum_editor_webgl/index.html;
    }
}
